Book.destroy_all
User.destroy_all


user = User.create!(email: "test2@gmail.com", password:"o3if4jr", address:"amsterdam", remote_photo_url: 'https://upload.wikimedia.org/wikipedia/en/9/94/Samantha_Jones_by_Kim_Cattrall.jpg', name: 'Samantha')
user1 = User.create!(email: "test3@gmail.com", password:"123456", address:"amsterdam", remote_photo_url: 'https://vignette.wikia.nocookie.net/degrassi/images/0/05/1-29CNSPhoto.jpg/revision/latest?cb=20140525205812', name: 'Big')
user2 = User.create!(email: "test4@gmail.com", password:"123456", address:"paris", remote_photo_url: 'https://vignette.wikia.nocookie.net/degrassi/images/0/05/1-29CNSPhoto.jpg/revision/latest?cb=20140525205812', name: 'Biggot')

Book.create!(title: "Mrs. Halloway", remote_photo_url: "https://prodimage.images-bn.com/pimages/9780156628709_p0_v7_s550x406.jpg", user: user, author: "Virginia Woolf", description: "Mrs Dalloway is a novel by Virginia Woolf that details a day in the life of Clarissa Dalloway, a fictional high-society woman in post–First World War England. It is one of Woolf's best-known novels.")
Book.create!(title: "Harry Potter and the Chamber of Secrets", user: user, author: "J. K. Rowling", remote_photo_url: "https://hpmedia.bloomsbury.com/rep/s/9781408855904_309575.jpeg", description: "The second instalment of boy wizard Harry Potter's adventures at Hogwarts School of Witchcraft and Wizardry, based on the novel by JK Rowling. A mysterious elf tells Harry to expect trouble during his second year at Hogwarts, but nothing can prepare him for trees that fight back, flying cars, spiders that talk and deadly warnings written in blood on the walls of the school.")
Book.create!(title: "The Name Of the Wind", user: user, author: "Patrick Rothfuss", remote_photo_url: "The Name of the Wind, also called The Kingkiller Chronicle: Day One, is a fantasy novel written by American author Patrick Rothfuss. It is the first book in the ongoing fantasy trilogy The Kingkiller Chronicle, followed by The Wise Man's Fear. It was published on March 27, 2007 by DAW Books.")

Book.create!(title: "Harry Potter and the Sorcerer's Stone", remote_photo_url: "https://images-na.ssl-images-amazon.com/images/I/51v1aAlA9xL._SX318_BO1,204,203,200_.jpg", user: user1, author: "J. K. Rowling", description: "Harry Potter and the Philosopher's Stone is a fantasy novel written by British author J. K. Rowling. The first novel in the Harry Potter series and Rowling's debut novel, it follows Harry Potter, a young wizard who discovers his magical heritage on his eleventh birthday, when he receives a letter of acceptance to Hogwarts School of Witchcraft and Wizardry. Harry makes close friends and a few enemies during his first year at the school, and with the help of his friends, Harry faces an attempted comeback by the dark wizard Lord Voldemort, who killed Harry's parents, but failed to kill Harry when he was just 15 months old.")
Book.create!(title: "Harry Potter and the Chamber of Secrets", user: user1, author: "J. K. Rowling", remote_photo_url: "https://hpmedia.bloomsbury.com/rep/s/9781408855683_309032.jpeg", description: "The second instalment of boy wizard Harry Potter's adventures at Hogwarts School of Witchcraft and Wizardry, based on the novel by JK Rowling. A mysterious elf tells Harry to expect trouble during his second year at Hogwarts, but nothing can prepare him for trees that fight back, flying cars, spiders that talk and deadly warnings written in blood on the walls of the school.")
Book.create!(title: "The Name Of the Wind", user: user1, author: "Patrick Rothfuss", remote_photo_url: "The Name of the Wind, also called The Kingkiller Chronicle: Day One, is a fantasy novel written by American author Patrick Rothfuss. It is the first book in the ongoing fantasy trilogy The Kingkiller Chronicle, followed by The Wise Man's Fear. It was published on March 27, 2007 by DAW Books.")

Book.create!(title: "Harry Potter and the Sorcerer's Stone", remote_photo_url: "https://kbimages1-a.akamaihd.net/3923e3c0-2296-4f4f-96a4-69700eca44f5/1200/1200/False/harry-potter-and-the-sorcerer-s-stone-the-first-book-in-the-phenomenal-internationally-bestselling-harry-potter-series-by-j-k-rowling.jpg", user: user2, author: "J. K. Rowling", description: "Harry Potter and the Philosopher's Stone is a fantasy novel written by British author J. K. Rowling. The first novel in the Harry Potter series and Rowling's debut novel, it follows Harry Potter, a young wizard who discovers his magical heritage on his eleventh birthday, when he receives a letter of acceptance to Hogwarts School of Witchcraft and Wizardry. Harry makes close friends and a few enemies during his first year at the school, and with the help of his friends, Harry faces an attempted comeback by the dark wizard Lord Voldemort, who killed Harry's parents, but failed to kill Harry when he was just 15 months old.")
Book.create!(title: "Harry Potter and the Chamber of Secrets", user: user1, author: "J. K. Rowling", remote_photo_url: "https://prodimage.images-bn.com/pimages/9781338299144_p0_v4_s550x406.jpg", description: "The second instalment of boy wizard Harry Potter's adventures at Hogwarts School of Witchcraft and Wizardry, based on the novel by JK Rowling. A mysterious elf tells Harry to expect trouble during his second year at Hogwarts, but nothing can prepare him for trees that fight back, flying cars, spiders that talk and deadly warnings written in blood on the walls of the school.")
Book.create!(title: "Harry Potter and the Philosopher's Stone", user: user2, author: "J. K. Rowling", remote_photo_url: "https://upload.wikimedia.org/wikipedia/en/thumb/6/6b/Harry_Potter_and_the_Philosopher%27s_Stone_Book_Cover.jpg/220px-Harry_Potter_and_the_Philosopher%27s_Stone_Book_Cover.jpg", description: "Harry Potter and the Philosopher's Stone is a fantasy novel written by British author J. K. Rowling. The first novel in the Harry Potter series and Rowling's debut novel, it follows Harry Potter, a young wizard who discovers his magical heritage on his eleventh birthday, when he receives a letter of acceptance to Hogwarts School of Witchcraft and Wizardry. Harry makes close friends and a few enemies during his first year at the school, and with the help of his friends, Harry faces an attempted comeback by the dark wizard Lord Voldemort, who killed Harry's parents, but failed to kill Harry when he was just 15 months old.")
Book.create!(title: "test", remote_photo_url: "https://prodimage.images-bn.com/pimages/9780156628709_p0_v7_s550x406.jpg", user: user, author: "Virginia Woolf", description: "Mrs Dalloway is a novel by Virginia Woolf that details a day in the life of Clarissa Dalloway, a fictional high-society woman in post–First World War England. It is one of Woolf's best-known novels.")

