Book.destroy_all
User.destroy_all


user = User.create!(email: "test2@gmail.com", password:"o3if4jr", address:"amsterdam", remote_photo_url: 'https://upload.wikimedia.org/wikipedia/en/9/94/Samantha_Jones_by_Kim_Cattrall.jpg', name: 'Samantha')
user1 = User.create!(email: "test5@gmail.com", password:"123456", address:"amsterdam", remote_photo_url: 'https://vignette.wikia.nocookie.net/degrassi/images/0/05/1-29CNSPhoto.jpg/revision/latest?cb=20140525205812', name:'Big')
user2 = User.create!(email: "test4@gmail.com", password:"123456", address:"paris", remote_photo_url: 'https://vignette.wikia.nocookie.net/degrassi/images/0/05/1-29CNSPhoto.jpg/revision/latest?cb=20140525205812', name: 'Biggot')

Book.create!(title: "Sapiens: a brief history of humankind", remote_photo_url: "https://upload.wikimedia.org/wikipedia/en/d/d2/Sapiens_A_Brief_History_of_Humankind.jpg", user: user, author: "Yuval Noah Harari", description: "'Sapiens' is a short telling of the entire human history, from pre-anatomically modern humans through the agricultural and scientific revolutions and to the present.
.")
Book.create!(title: "Norwegian Wood", user: user, author: "Haruki Murakami", remote_photo_url: "https://s.s-bol.com/imgbase0/imagebase3/extralarge/FC/0/1/3/7/9200000020987310.jpg", description: "Norwegian Wood is the story of Toru Watanabe, a young man who is damaged by the suicide of his high school friend, Kizuki. Toru falls in love with Kizuki's tortured girlfriend, Naoko, who is isolated in her own mind. When she goes into a mental hospital, he promises to wait for her.")
Book.create!(title: "The Dutch House", remote_photo_url: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1552334367l/44318414.jpg", user: user, author: "Ann Patchett", description: "At the end of the Second World War, Cyril Conroy combines luck and a single canny investment to begin an enormous real estate empire, propelling his family from poverty to enormous wealth. His first order of business is to buy the Dutch House, a lavish estate in the suburbs outside of Philadelphia.")
Book.create!(title: "Harry Potter and the Chamber of Secrets", user: user, author: "J. K. Rowling", remote_photo_url: "https://hpmedia.bloomsbury.com/rep/s/9781408855904_309575.jpeg", description: "The second instalment of boy wizard Harry Potter's adventures at Hogwarts School of Witchcraft and Wizardry, based on the novel by JK Rowling. A mysterious elf tells Harry to expect trouble during his second year at Hogwarts, but nothing can prepare him for trees that fight back, flying cars, spiders that talk and deadly warnings written in blood on the walls of the school.")
Book.create!(title: "Nineteen Eighty-Four", remote_photo_url: "https://snewd.com/wp-content/uploads/2020/01/1984-min-642x1024.jpg", user: user, author: "George Orwell", description: "A dystopian novella by George Orwell published in 1949, which follows the life of Winston Smith, a low ranking member of 'the Party', who is frustrated by the omnipresent eyes of the party, and its ominous ruler Big Brother. 'Big Brother' controls every aspect of people's lives.")
Book.create!(title: "The Secret of Yoga Sutra", remote_photo_url: "https://cdn.shopify.com/s/files/1/0092/7562/products/Practice_of_the_Yoga_Sutra_1200_x_1800_640x.png", user: user, author: "Pandit Rajmani Tigunait", description: "The Yoga Sutra is the living source wisdom of the yoga tradition, and is as relevant today as it was 2,200 years ago when it was codified by the sage Patanjali. Using this ancient yogic text as a guide, we can unlock the hidden power of yoga, and experience the promise of yoga in our lives.")
Book.create!(title: "The Sun and Her Flowers", user: user, author: "Rupi Kaur", remote_photo_url: "https://images-na.ssl-images-amazon.com/images/I/41pTlqdnhgL._SX326_BO1,204,203,200_.jpg", description: "The Sun and Her Flowers is Rupi Kaur's second collection of poetry, published in 2017. It is composed of five chapters, with illustrations by the author.")
Book.create!(title: "Harry Potter and the Philosopher's Stone", user: user2, author: "J. K. Rowling", remote_photo_url: "https://upload.wikimedia.org/wikipedia/en/thumb/6/6b/Harry_Potter_and_the_Philosopher%27s_Stone_Book_Cover.jpg/220px-Harry_Potter_and_the_Philosopher%27s_Stone_Book_Cover.jpg", description: "Harry Potter and the Philosopher's Stone is a fantasy novel written by British author J. K. Rowling. The first novel in the Harry Potter series and Rowling's debut novel, it follows Harry Potter, a young wizard who discovers his magical heritage on his eleventh birthday, when he receives a letter of acceptance to Hogwarts School of Witchcraft and Wizardry. Harry makes close friends and a few enemies during his first year at the school, and with the help of his friends, Harry faces an attempted comeback by the dark wizard Lord Voldemort, who killed Harry's parents, but failed to kill Harry when he was just 15 months old.")
Book.create!(title: "Mrs. Halloway", remote_photo_url: "https://prodimage.images-bn.com/pimages/9780156628709_p0_v7_s550x406.jpg", user: user, author: "Virginia Woolf", description: "Mrs Dalloway is a novel by Virginia Woolf that details a day in the life of Clarissa Dalloway, a fictional high-society woman in post–First World War England. It is one of Woolf's best-known novels.")

